import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import graphQLClient from '../GraphQL/graphQLClient'
import { ALL_ITEMS_DATA } from '../GraphQL/queries'

export const getStaticProps: GetStaticProps = async () => {
  const data = await graphQLClient.request(ALL_ITEMS_DATA);

  return {
    props: { data }
  };
}

const Home: NextPage = ({data}: any) => {
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          {data.item.children.results.map((item: any) => (
            <a key={item.id} href="https://nextjs.org/docs" className={styles.card}>
              <h2>{item.name} &rarr;</h2>
              <p>{item.id}</p>
            </a>
          ))}          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
